### PR TITLE
Added NodeJS and NPM

### PR DESCRIPTION
**Pull request by eddiejibson**
Small addition, but lovely nevertheless.

### CODE REVIEW

**Comment by timmyrs** [comment]
Thanks for your submission, unfortunately, tho, you seem to have made some errors in your JSON syntax:

1. Maximum stack depth exceeded in **packages.json**

Feel free to reopen the pull request once you've gotten rid of all syntax errors.

**Comment by timmyrs** [comment]
Thanks for your submission, unfortunately, tho, you seem to have made some errors in your JSON syntax:

1. Maximum stack depth exceeded in **packages.json**

Feel free to reopen the pull request once you've gotten rid of all syntax errors.

**Comment by eddiejibson** [comment]
Fixed

**Comment by eddiejibson** [comment]
#1

**Pull request closed without merging**
